-- MySQL Script generated by MySQL Workbench
-- mer. 12 déc. 2018 14:47:58 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema transfer_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transfer_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transfer_db` ;
USE `transfer_db` ;

-- -----------------------------------------------------
-- Table `transfer_db`.`expediteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfer_db`.`expediteur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transfer_db`.`destinataire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfer_db`.`destinataire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transfer_db`.`info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfer_db`.`info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date envoi` DATE NULL,
  `message` VARCHAR(255) NULL,
  `date reception` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transfer_db`.`fichier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfer_db`.`fichier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `expediteur` VARCHAR(45) NULL,
  `taille` INT NULL,
  `url` VARCHAR(255) NULL,
  `key` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transfer_db`.`expediteur_has_fichier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfer_db`.`expediteur_has_fichier` (
  `expediteur_id` INT NOT NULL,
  `fichier_id` INT NOT NULL,
  PRIMARY KEY (`expediteur_id`, `fichier_id`),
  INDEX `fk_expediteur_has_fichier_fichier1_idx` (`fichier_id` ASC) ,
  INDEX `fk_expediteur_has_fichier_expediteur1_idx` (`expediteur_id` ASC) ,
  CONSTRAINT `fk_expediteur_has_fichier_expediteur1`
    FOREIGN KEY (`expediteur_id`)
    REFERENCES `transfer_db`.`expediteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expediteur_has_fichier_fichier1`
    FOREIGN KEY (`fichier_id`)
    REFERENCES `transfer_db`.`fichier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transfer_db`.`fichier_has_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfer_db`.`fichier_has_info` (
  `fichier_id` INT NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`fichier_id`, `info_id`),
  INDEX `fk_fichier_has_info_info1_idx` (`info_id` ASC) ,
  INDEX `fk_fichier_has_info_fichier1_idx` (`fichier_id` ASC) ,
  CONSTRAINT `fk_fichier_has_info_fichier1`
    FOREIGN KEY (`fichier_id`)
    REFERENCES `transfer_db`.`fichier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fichier_has_info_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `transfer_db`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transfer_db`.`destinataire_has_fichier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfer_db`.`destinataire_has_fichier` (
  `destinataire_id` INT NOT NULL,
  `fichier_id` INT NOT NULL,
  PRIMARY KEY (`destinataire_id`, `fichier_id`),
  INDEX `fk_destinataire_has_fichier_fichier1_idx` (`fichier_id` ASC) ,
  INDEX `fk_destinataire_has_fichier_destinataire1_idx` (`destinataire_id` ASC) ,
  CONSTRAINT `fk_destinataire_has_fichier_destinataire1`
    FOREIGN KEY (`destinataire_id`)
    REFERENCES `transfer_db`.`destinataire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destinataire_has_fichier_fichier1`
    FOREIGN KEY (`fichier_id`)
    REFERENCES `transfer_db`.`fichier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
